[Docs] Remove stack trace reference
exercism/automated-tests pull request #43
Opened 2020-01-30 13:45 UTC by ErikSchierboom

I think it might make sense to remove it here. If track's want to add it, they can, but I feel like we should not necessarily encourage including stack traces.

2020-01-30 20:49 UTC, iHiD commented
I think we should see what a load of tracks do and then edit this documentation with some good examples of what works. I really think some consistency is important, but I don't yet understand the consistent thing that we should do.

2020-01-31 13:41 UTC, ErikSchierboom commented
I understand, but my thought was not to encourage using stack traces. IMHO it should be a last resort, due the problems with it (filtering unneeded lines, etc.).

2020-04-09 18:22 UTC, kotp requested changes
This will keep it explicit that the stack trace is not encouraged, in fact discouraged.

2020-04-09 18:22 UTC, kotp commented on docs/interface.md
> +Where the status is `error` (the tests fail to execute cleanly), the top level `message` key should be provided. It should provide the occurring error to the user. As it is the only piece of informat
```suggestion
Where the status is `error` (the tests fail to execute cleanly), the top level `message` key should be provided. It should provide the occurring error to the user. As it is the only piece of information a user will receive on how to debug their issue, it must be as clear as possible.. For example, in Ruby, in the case of a syntax error, we provide the error without a stack trace. In compiled languages, the compilation error should be provided.
```

2020-04-09 22:46 UTC, iHiD commented
@kotp Thanks for reinitiating the discussion.

---

I don't know where your thinking on this has got to @ErikSchierboom?

I think Stack Traces are really important but only in error cases (either exceptions or compilation errors) and that we remove reference to the code files etc. That's where I'd edge too.

2020-04-10 07:37 UTC, ErikSchierboom commented
> I think Stack Traces are really important but only in error cases (either exceptions or compilation errors) and that we remove reference to the code files etc. That's where I'd edge too.

I think stack traces are only important if the default error message is not enough for the student to figure things out. If somehow this is the case, we could present a trimmed, sanitized stack trace, but I'd prefer this to be the last resort. It is all too easy for a stack trace to include sensitive information that the sanitation process does not catch. So I'd argue for a: don't use unless you have a very good reason to do so. The reason being that it makes things easier is not good enough for me, if the student should also be able to figure things out without the stack trace.

2020-11-25 17:33 UTC, iHiD commented
@ErikSchierboom Let's push this to the v3-docs instead.

2021-08-30 10:24 UTC, closed without merging